BEGIN;

CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.obras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    numero VARCHAR(50),
    localizacao VARCHAR(255),
    data_cadastro DATE,
    sistema_coordenadas VARCHAR(10) NOT NULL DEFAULT 'local',
    responsavel_tecnico VARCHAR(255),
    observacoes TEXT,
    foto_url TEXT,
    legenda_foto VARCHAR(255),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_obras_sistema_coordenadas
        CHECK (sistema_coordenadas IN ('local', 'utm'))
);

CREATE INDEX IF NOT EXISTS ix_obras_nome
    ON app.obras (nome);

CREATE INDEX IF NOT EXISTS ix_obras_numero
    ON app.obras (numero);

CREATE OR REPLACE FUNCTION app.definir_atualizado_em()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_obras_definir_atualizado_em
    ON app.obras;

CREATE TRIGGER trg_obras_definir_atualizado_em
BEFORE UPDATE ON app.obras
FOR EACH ROW
EXECUTE FUNCTION app.definir_atualizado_em();

COMMIT;
